#!/bin/bash

absdir() {                                               
  echo "$(cd "$(dirname "$1")" && pwd)/"
}

dir=${1:-sakai}

prog_dir=$(absdir $0)
# Use trunk as we need to merge in a module called master
git clone --single-branch --branch trunk ./repos/sakai.git $dir
cd $dir


cat .externals| grep -v '^#' | tr -s '\n'| cut -d' ' -f1 |sort|\
#head -2 |\
while read directory
  do echo $directory
  # Samigo doesn't match it's directory and repository name.
  module=$(echo $directory | sed 's/samigo/sam/')
  # Add a remote for the submodule
  git remote add $module-sakai ../repos/$module.git
  # Fetch the trunk branch from the remote
  git fetch $module-sakai trunk
  # Create a branch todo work on based on the trunk branch from the remote
  git branch -f tmp-$module $module-sakai/trunk
  # Re-write history so it always looks like it was in that folder
  # This is slow....
  git filter-branch --prune-empty --tree-filter "$prog_dir/move-to-folder $directory" -- tmp-$module
  # Rename our working branch to be the original
  git branch -M tmp-$module $module

  git for-each-ref --format="%(refname)" refs/original/ |\
   xargs -n 1 git update-ref -d
  #git read-tree -m -u $module-sakai/trunk
  #git merge --no-commit $module-sakai/trunk
  #git commit -m "Subtree $module merged"
done

#git prune
