#!/bin/bash

dir=${1:-sakai}

git clone --single-branch ./repos/sakai.git $dir
cd $dir

cat .externals| grep -v '^#' | tr -s '\n'| cut -d' ' -f1 |sort | \
head -2 |\
while read directory
  do echo $directory
  # Samigo doesn't match it's directory and repository name.
  module=$(echo $directory | sed 's/samigo/sam/')
  git remote add $module-sakai ../repos/$module.git
  git fetch $module-sakai trunk
  # Re-write history so it always looks like it was in that folder
  # This is slow....
  git filter-branch --prune-empty --tree-filter "
if [[ ! -e $directory ]]; then
    mkdir -p $directory
    git ls-tree --name-only \$GIT_COMMIT | xargs -I files mv files $directory
fi" -- $module-sakai/trunk

  git for-each-ref --format="%(refname)" refs/original/ |\
   xargs -n 1 git update-ref -d
  git read-tree -u $module-sakai/trunk
  #git merge -s ours --no-commit $module-sakai/trunk
  #git commit -m "Subtree $module merged"
done
#git prune
